# .github/workflows/python-app.yml
name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest pytest-cov pytest-mock httpx requests-mock
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Setup test environment
      run: |
        cp .env.sample .env
        sed -i 's/SUPABASE_URL=.*/SUPABASE_URL=https:\/\/example.supabase.co/g' .env
        sed -i 's/SUPABASE_KEY=.*/SUPABASE_KEY=mock-key/g' .env
        sed -i 's/SUPABASE_SERVICE_KEY=.*/SUPABASE_SERVICE_KEY=mock-service-key/g' .env
        
    - name: Test with pytest
      run: |
        pytest --cov=app tests/ --cov-report=xml
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        fail_ci_if_error: false

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: compatibility-matrix-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max